import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import localFont from "next/font/local"
const kyiv = localFont({
  src: [
    {
      path: '../public/font/kyiv-type-sans/KyivTypeSans-Medium-.otf',
      weight: '400',
      style: 'medium',
    },
    {
      path: '../public/font/kyiv-type-sans/KyivTypeSans-Regular-.otf',
      weight: '300',
      style: 'regular',
    },
    {
      path: '../public/font/kyiv-type-sans/KyivTypeSans-Light-.otf',
      weight: '200',
      style: 'light',
    },
    {
      path: '../public/font/kyiv-type-sans/KyivTypeSans-Thin.otf',
      weight: '100',
      style: 'thin',
    },
    {
      path: '../public/font/kyiv-type-sans/KyivTypeSans-Bold-.otf',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../public/font/kyiv-type-sans/KyivTypeSans-Black-.otf',
      weight: '800',
      style: 'black',
    },
  ],

});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <div className={`${kyiv.className} bg-fixed bg-primary-bg`}>
        <Navbar></Navbar>
        {children}
      </div>
    </html>
  );
}
